name: Simple Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type DELETE to confirm'
        required: true
        default: ''

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DELETE'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Destroy
      working-directory: terraform
      run: |
        terraform init
        terraform destroy -auto-approve
